add_rules("mode.debug", "mode.release")

target("BingBackground")
    add_rules("qt.console")
    add_frameworks("QtCore", "QtWidgets", "QtGui","QtNetwork")
    add_files("resources/resources.qrc")
    add_files("src/*.cpp")
    add_files("src/WallpaperInfo.h")
    add_files("src/WallpaperDown.h")
    add_files("src/Wallpaper.h")
